src/Entity/Article.php
<?php

namespace App\Entity;

use App\Repository\ArticleRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ArticleRepository::class)]
class Article
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 150)]
    private ?string $title = null;

    #[ORM\Column(length: 255)]
    private ?string $content = null;

    #[ORM\Column]
    private ?bool $is_published = false;

    #[ORM\Column(length: 255)]
    private ?string $slug = null;

    #[ORM\Column(type: "string", length: 255)]
    private ?string $image;

    #[ORM\ManyToOne(inversedBy: 'articles')]
    private ?User $author = null;

    #[ORM\OneToMany(mappedBy: 'article', targetEntity: Comments::class)]
    private Collection $comments;

    public function __construct()
    {
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return string|null
     */
    public function getSlug(): ?string
    {
        return $this->slug;
    }

    /**
     * @param string|null $slug
     */
    public function setSlug(?string $slug): self
    {
        $this->slug = $slug;
        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function __toString() :string
    {
        return $this->title;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function isIsPublished(): ?bool
    {
        return $this->is_published;
    }

    public function setIsPublished(bool $is_published): self
    {
        $this->is_published = $is_published;

        return $this;
    }

    public function getAuthor(): ?user
    {
        return $this->author;
    }

    public function setAuthor(?user $author): self
    {
        $this->author = $author;

        return $this;
    }

    /**
     * @return Collection<int, Comments>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comments $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments->add($comment);
            $comment->setArticle($this);
        }

        return $this;
    }

    public function removeComment(Comments $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getArticle() === $this) {
                $comment->setArticle(null);
            }
        }

        return $this;
    }

    /**
     * @return string|null
     */
    public function getImage(): ?string
    {
        return $this->image;
    }

    /**
     * @param string|null $image
     * @return Article
     */
    public function setImage(?string $image): self
    {
        $this->image = $image;
        return $this;
    }

}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use App\Repository\ArticleRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class HomeController extends AbstractController
{
    #[Route('/', name: 'home')]
    public function index(ArticleRepository $articleRepository): Response
    {
        return $this->render('home/index.html.twig', [
            'articles' => $articleRepository->findAll()
        ]);
    }
}

templates/home/index.html.twig
{% extends 'base.html.twig' %}
{% import '_macros/alert.html.twig' as Dialog %}

{% block title %}Home !{% endblock %}

{% block body %}

    {% if app.user %} <h1>{{ Dialog.alert('Bonjour' ~' '~ app.user.email, 'warning') }}</h1>
        <div id="contain-avatar">
            <img id="avatar" src="upload.directory/{{ (app.user.avatar) }}" alt="" >
        </div>
    {% else%}
            {{  Dialog.alert('Bonjour', 'warning') }}
    {% endif %}

    <header>
        {% if app.user %}
            {% if is_granted('ROLE_AUTHOR') %}
                <button class="btn btn-primary"><a class="color-text" href="{{ path('article_add') }}">{{ 'Add a new article'|trans }}</a></button>
            {% endif %}
            {% if is_granted('ROLE_ADMIN') %}<button class="btn btn-primary"><a class="color-text" href="/admin">{{ 'Admin' }}</a></button>{% endif %}
            <button class="btn btn-primary"><a class="color-text" href="{{ path('app_user') }}">Profil</a></button>
            <button class="btn btn-primary"><a class="color-text" href="{{ path('app_logout') }}">{{ 'Logout'|trans }}</a></button>


            {% else %}
                <button class="btn btn-primary"><a class="color-text" href="{{ path('app_login') }}">{{ 'Login' | trans}}</a></button>
                <button class="btn btn-primary"><a class="color-text" href="{{ path('app_register') }}">{{ 'Register' | trans }}</a></button>
        {% endif %}

    </header>

    <div class="container">
        {% if articles is defined %}
            {% for article in articles %}
                {% if article.isPublished %}
                    <div class="content-art">
                        <h1 class="title-article">{{ article.title  }}</h1>
                        <div class="image-cover">
                            <img id="image" src="upload.directory/{{ (article.image) }}" alt="">
                        </div>
                        <p>{{ article.content }}</p>
                        <p class="author">{{ article.author }}</p>
                        <a href="{{ path('comments_add', {id: article.id}) }}">{{ 'Add a comment'|trans}}</a>
                        {% if is_granted('ROLE_AUTHOR') %}
                            <a href="{{ path('article_edit', {'id': article.id}) }}">{{ 'Edit' | trans }}</a>
                            <a  href="{{ path('article_delete', {'id': article.id}) }}">{{ 'Delete' | trans }}</a>
                        {% endif %}
                        <h1 class="comments">Commentaires: </h1>
                        {% for comment in article.comments %}
                            <div class="content-comm">
                                <p>{{ comment.content }}</p>
                                <p>{{ comment.user.email }}</p>
                                {% if is_granted('ROLE_MODERATOR') %}
                                    <a href="{{ path('comments_edit', {'id': comment.id}) }}"></a>
                                    <a href="{{ path('comments_delete', {'id': comment.id}) }}">{{ 'Delete' | trans }}</a>
                                {% endif %}
                            </div>

                        {% endfor %}
                    </div>

                {% endif %}
            {% endfor %}
        {% endif %}

    </div>

{% endblock %}